### ISSUE TITLE
dalao有docker地址吗？不好部署

### ISSUE THREAD

**Issue by openwrt36** [ChinaArJun/jd_seckill_docker#1]
RT

**Comment by m20104600** [comment]
我是完全不晓得怎么部署

**Comment by ChinaArJun** [comment]
> 我是完全不晓得怎么部署

已经更新了docker地址，项目底部有说明

**Comment by m20104600** [comment]
[url=https://sm.ms/image/p1IzKmeahxFVJtf][img]https://i.loli.net/2021/01/06/p1IzKmeahxFVJtf.png[/img][/url]
