### ISSUE TITLE
eid和fp怎么获取，有截图说明吗

### ISSUE THREAD

**Issue by wyj999** [ChinaArJun/jd_seckill_docker#2]

**Comment by wyj999** [comment]
在京东的购物车F12调出开发者模式

选择商品，点击结算，进入结算页面后。

在结算页面F12的Sources内右侧watch，点击加号填入_JdTdudfp，即可看到该参数的内容，edi与fp均在其中

第一步：进入京东结算页面

第二步：f12打开Sources

第三步：右侧的watch，点击加号，填入_JdTdudfp

即可看到_JdTdudfp:Object

**Comment by ChinaArJun** [comment]
> 在京东的购物车F12调出开发者模式
> 
> 选择商品，点击结算，进入结算页面后。
> 
> 在结算页面F12的Sources内右侧watch，点击加号填入_JdTdudfp，即可看到该参数的内容，edi与fp均在其中
> 
> 第一步：进入京东结算页面
> 
> 第二步：f12打开Sources
> 
> 第三步：右侧的watch，点击加号，填入_JdTdudfp
> 
> 即可看到_JdTdudfp:Object

这个可以不用配置
