### ISSUE TITLE
docker无法拉取

### ISSUE THREAD

**Issue by foreverlong** [ChinaArJun/jd_seckill_docker#5]
Pulling jd-seckill (jd-seckill:latest)...
Trying to pull repository docker.io/library/jd-seckill ...
ERROR: repository docker.io/jd-seckill not found: does not exist or no pull access
请问这个报错如何解决呢？

**Comment by ChinaArJun** [comment]
> Pulling jd-seckill (jd-seckill:latest)...
> Trying to pull repository docker.io/library/jd-seckill ...
> ERROR: repository docker.io/jd-seckill not found: does not exist or no pull access
> 请问这个报错如何解决呢？

更新一下代码
应该拉去chinaarjun/jd-seckill-docker镜像

**Comment by axhiao** [comment]
请问老哥抢到了吗？
