### ISSUE TITLE
docker build jd-seckill:latest . 这步不能运行啊？

### ISSUE THREAD

**Issue by shenzt68** [ChinaArJun/jd_seckill_docker#9]
如题
出现：
root@amlogic:~/jd_seckill_docker/dockerfile# docker build jd-seckill:latest .
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile

**Comment by hanxuanliang** [comment]
docker build -t jd-seckill:latest .

**Comment by hanxuanliang** [comment]
但是现在的问题是 dockerfile 里面的git没有了
